version: '3.7'

services:
  paper:
    build: .
    container_name: debug_auto_reloader
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
      - 5005:5005
    volumes:
      - ./.docker:/data
    entrypoint:
      - /docker-setup-plugin
      - https://github.com/noonmaru/kotlin-plugin/releases/download/1.4.10/kotlin-1.4.10.jar